version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.0-browsers
    working_directory: ~/src
    steps:
      - checkout # special step to check out source code to working directory
      - restore_cache: # special step to restore the dependency cache
          keys:
            - project-{{ .Branch }}-{{ checksum "package.json" }}
            - project-{{ .Branch }}
            - project
      - run:
          name: install dependencies
          command: yarn install
      - save_cache: # special step to save the dependency cache
          key: project-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.yarn
            - ~/.cache
      - run:
          name: "Run Jest and Collect Coverage Reports"
          command: test --collectCoverage=true
      - store_artifacts:
          path: coverage
#      - run:
#          name: test e2e
#          command: $(npm bin)/cypress run
      - run:
          name: lint
          command: yarn run lint
      - run:
          name: stylelint
          command: yarn run stylelint
